# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181007_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media', width_field='width_field'),
        ),
    ]
