# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181007_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 10, 15, 10, 9, 51, 132687, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
